BASE64_IMAGE_EMPTY = 'R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
BASE64_AUDIO_EMPTY = 'UklGRigAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhAgAAAAEA'
AUDIO_EXTENTIONS = ['wav', 'mp3', 'flac', 'ogg', 'aac', 'm4a']